export const constants = {
    SET_CUSTOMERS: 'SET_CUSTOMERS',
    ADD_CUSTOMER: 'ADD_CUSTOMER',
    UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
    DELETE_CUSTOMER: 'DELETE_CUSTOMER',
    ADD_ACCOUNT: 'ADD_ACCOUNT',
    DELETE_ACCOUNT: 'DELETE_ACCOUNT',
    UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
    SAVE_EMPLOYER: 'SAVE_EMPLOYER',
    SET_EMPLOYERS: 'SET_EMPLOYERS'
}